# Generated by Django 3.0.5 on 2020-04-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Inisponível')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Inisponível')], max_length=100)),
                ('ingredientes', models.ManyToManyField(to='dashboard.Ingrediente')),
            ],
        ),
    ]
