# Generated by Django 3.0.5 on 2020-04-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.FileField(null=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
