# Generated by Django 3.0.5 on 2020-04-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200405_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.FileField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
