# Generated by Django 2.2.7 on 2020-04-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200405_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Produto')),
            ],
        ),
    ]
