# Generated by Django 2.2.7 on 2020-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200411_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtopedido',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
