# Generated by Django 2.2.7 on 2020-04-12 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_auto_20200411_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('referencia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('enderecos', models.ManyToManyField(to='dashboard.Endereco')),
                ('user', models.OneToOneField(on_delete='cascade', related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
